version: '3.8'

services:
  postgres:
    container_name: events_postgres
    image: postgis/postgis:15-3.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: event_management
    networks:
      - event_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d event_management"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  event_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local